# Generated by Django 2.1.7 on 2019-04-02 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='authgroup',
            table='old_auth_group',
        ),
        migrations.AlterModelTable(
            name='authgrouppermissions',
            table='old_auth_group_permissions',
        ),
        migrations.AlterModelTable(
            name='authpermission',
            table='old_auth_permission',
        ),
        migrations.AlterModelTable(
            name='authuser',
            table='old_auth_user',
        ),
        migrations.AlterModelTable(
            name='authusergroups',
            table='old_auth_user_groups',
        ),
        migrations.AlterModelTable(
            name='authuseruserpermissions',
            table='old_auth_user_user_permissions',
        ),
    ]
