# Generated by Django 2.1.7 on 2019-04-02 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190402_1147'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='djangoadminlog',
            table='old_django_admin_log',
        ),
        migrations.AlterModelTable(
            name='djangocontenttype',
            table='old_django_content_type',
        ),
        migrations.AlterModelTable(
            name='djangosession',
            table='old_django_session',
        ),
        migrations.AlterModelTable(
            name='djangosite',
            table='old_django_site',
        ),
    ]
