# Generated by Django 2.1.7 on 2019-04-02 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190402_1148'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='authgroup',
            table='auth_group',
        ),
        migrations.AlterModelTable(
            name='authgrouppermissions',
            table='auth_group_permissions',
        ),
        migrations.AlterModelTable(
            name='authpermission',
            table='auth_permission',
        ),
        migrations.AlterModelTable(
            name='authuser',
            table='auth_user',
        ),
        migrations.AlterModelTable(
            name='authusergroups',
            table='auth_user_groups',
        ),
        migrations.AlterModelTable(
            name='authuseruserpermissions',
            table='auth_user_user_permissions',
        ),
        migrations.AlterModelTable(
            name='djangoadminlog',
            table='django_admin_log',
        ),
        migrations.AlterModelTable(
            name='djangocontenttype',
            table='django_content_type',
        ),
        migrations.AlterModelTable(
            name='djangosession',
            table='django_session',
        ),
        migrations.AlterModelTable(
            name='djangosite',
            table='django_site',
        ),
    ]
