# Generated by Django 2.1.7 on 2019-04-02 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190402_1155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poemspost',
            options={},
        ),
    ]
