# Generated by Django 2.1.7 on 2019-04-02 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190402_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='poemspost',
            name='author_fullname',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='poemspost',
            name='author_userrname',
            field=models.CharField(default='', max_length=200),
        ),
    ]
