# Generated by Django 2.1.7 on 2019-04-02 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190402_1201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poemscategorypost',
            options={},
        ),
    ]
