# Generated by Django 2.1.7 on 2019-04-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190402_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='poemscategorypost',
            name='cat_raw_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poemscategorypost',
            name='post_raw_id',
            field=models.IntegerField(default=0),
        ),
    ]
