# Generated by Django 2.2 on 2019-04-04 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190404_0832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newpoemspost',
            old_name='author_userrname',
            new_name='author_username',
        ),
    ]
