# Generated by Django 2.1.7 on 2019-04-02 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewPoemsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=110, unique=True)),
                ('created_at', models.DateTimeField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NewPoemsCategorypost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='posts.NewPoemsCategory')),
            ],
        ),
        migrations.CreateModel(
            name='NewPoemsPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_userrname', models.CharField(default='', max_length=200)),
                ('author_fullname', models.CharField(default='', max_length=200)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('slug', models.CharField(max_length=300, unique=True)),
                ('resource_html', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='newpoemscategorypost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='posts.NewPoemsPost'),
        ),
    ]
