# Generated by Django 2.1.7 on 2019-04-02 12:08

from django.db import migrations


def copy_old_db_to_new(apps, schema_editor):
    NewPoemsPost = apps.get_model('posts', 'NewPoemsPost')
    PoemsPost = apps.get_model('core', 'PoemsPost')

    for post in PoemsPost.objects.all():
        NewPoemsPost.objects.create(
            id=post.id,
            author_userrname=post.author_userrname,
            author_fullname=post.author_fullname,
            title=post.title,
            content=post.content,
            created_at=post.created_at,
            slug=post.slug,
            resource_html=post.resource_html,
        )

    NewPoemsCategory = apps.get_model('posts', 'NewPoemsCategory')
    PoemsCategory = apps.get_model('core', 'PoemsCategory')

    for cat in PoemsCategory.objects.all():
        NewPoemsCategory.objects.create(
            id=cat.id,
            name=cat.name,
            slug=cat.slug,
            created_at=cat.created_at,
            description=cat.description
        )

    NewPoemsCategorypost = apps.get_model('posts', 'NewPoemsCategorypost')
    PoemsCategorypost = apps.get_model('core', 'PoemsCategorypost')

    for post in PoemsCategorypost.objects.all():
        NewPoemsCategorypost.objects.create(
            id=post.id,
            post_id=post.post_raw_id,
            category_id=post.cat_raw_id,
            position=post.position,
            created_at=post.created_at
        )

class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('core', '0008_auto_20190402_0916'),
    ]

    operations = [
        migrations.RunPython(copy_old_db_to_new, migrations.RunPython.noop)
    ]
