# Generated by Django 2.2 on 2019-05-01 21:43

from django.conf import settings
from django.db import migrations


def populate_authors(apps, schema_editor):
    app, model = settings.AUTH_USER_MODEL.split('.')
    User = apps.get_model(app, model)
    Posts = apps.get_model('posts', 'NewPoemsPost')

    for post in Posts.objects.all():
        user, _ = User.objects.get_or_create(username=post.author_username)
        post.author = user
        post.save()


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_newpoemspost_author'),
    ]

    operations = [
        migrations.RunPython(populate_authors)
    ]
