# Generated by Django 2.2 on 2019-05-01 22:15

from django.db import migrations
from django.db import connection


def update_pg_sequences(apps, schema_editor):
    model_and_seqs = [
        ('NewPoemsCategorypost', 'posts_newpoemscategorypost_id_seq'),
        ('NewPoemsPost', 'posts_newpoemspost_id_seq'),
        ('NewPoemsCategory', 'posts_newpoemscategory_id_seq'),
    ]

    cursor = connection.cursor()
    for model_name, seq in model_and_seqs:
        Model = apps.get_model('posts', model_name)
        current = Model.objects.order_by('-id').first().id

        sql_statement = f"SELECT setval('{seq}', {current}, true);"
        cursor.execute(sql_statement)


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20190501_1902'),
    ]

    operations = [
        migrations.RunPython(update_pg_sequences, migrations.RunPython.noop),
    ]
